_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "3":
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 5
img_size:
    value: 224
lr:
    value: 2e-05
model:
    value: vit-base-patch16-224
